# Generated by Django 5.2.6 on 2025-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('baju jersey', 'Baju jersey'), ('celana', 'Celana'), ('sepatu', 'Sepatu'), ('bola', 'Bola'), ('botol minum', 'Botol Minum'), ('kaos kaki', 'Kaos kaki'), ('tas sepatu', 'Tas Sepatu')], default='baju jersey', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('new balance', 'New Balance'), ('asics', 'Asics')], default='nike', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
