# Generated by Django 5.2.6 on 2025-09-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shops_delete_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Products',
        ),
    ]
