# Generated by Django 5.2.6 on 2025-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
